### ISSUE TITLE
Feedback Task UTS

### ISSUE THREAD

**Issue by aufaroot18** [FixDev/task-backend-code#5]
## Feedback

- Thank you sudah mengerjakan final project.
- Sudah sesuai requirement.
- Terdapat authentikasi.

## Notes.

- Pada method `index`, sebaiknya lakukan pengecekan menggunakan `count` untuk menghitung apakah datanya ada atau tidak. Jika hanya dilakukan validasi `$patients`, statusnya akan bernilai true walaupun datanya kosong.
- Pada method `search`, sebaiknya berikan nama parameternya `name` dibandingkan `id` agar lebih representatif.
- Untuk mengetahui total data, dari pada melakukan query lagi ke database, sebaiknya gunakan `count` untuk menghitung hasil dari query sebelumnya (get). Jadi tidak perlu melakukan query dua kali sehingga lebih baik secara performance.

## Improvement

- Coba lakukan normalisasi pada database. Ex: Bisa membuat table terpisah untuk status pasien.
- Gunakan eloquent relationship jika sudah melakukan normalisasi.

**Comment by FixDev** [comment]
Notes feedback :
- Mungkin dibandingkan menggunakan `count` saya ganti pake `empty()` aja ya, jika pakai `count` khawatirnya jika data res dari databasenya banyak prosesnya akan jadi lama, karena kan kita cuma mau check dia empty atau enggak.

**Comment by FixDev** [comment]
Untuk improvement status patient sepertinya tidak perlu dibuat database baru, karena untuk status itu udah default hanya 3, yaitu : 
- Recovered
- Dead
- Positive
Mungkin saya hanya perlu ubah tipe data di databasenya jadi ENUM saja ya.

https://github.com/FixDev/task-backend-code/commit/5a170365efabb3ce8aea85b8506f8f38513ad094

**Comment by aufaroot18** [comment]
> Notes feedback :
> 
> * Dibandingkan menggunakan `count` saya ganti pake `empty()` aja ya, jika pakai `count` khawatirnya jika data res dari databasenya banyak prosesnya akan jadi lama, karena kan kita cuma mau check dia empty atau enggak.
> 
> [4fb0427](https://github.com/FixDev/task-backend-code/commit/4fb0427fb55c05fe7075bc5d56574cc2d1c74720)

Sorry, aku salah liat wkwk. Iya itu udah benar make `empty()` atau `count()`, buat ngecek jumlah data-nya.

**Comment by aufaroot18** [comment]
> Untuk improvement status patient sepertinya tidak perlu dibuat database baru, karena untuk status itu udah default hanya 3, yaitu :
> 
> * Recovered
> * Dead
> * Positive
>   Mungkin saya hanya perlu ubah tipe data di databasenya jadi ENUM saja ya.
> 
> [5a17036](https://github.com/FixDev/task-backend-code/commit/5a170365efabb3ce8aea85b8506f8f38513ad094)

Iyap, menggunakan enum juga bisa. Namun jika table-nya sudah kompleks, sudah sebaiknya memutuskan untuk dinormalisasi, dari pada menggunakan enum. But its depends on our project.

**Comment by FixDev** [comment]
Nice feedback bang, saya close ya issuenya xixix
